export const FETCH_ALL_CATEGORY_REQUEST = 'FETCH_ALL_CATEGORY_REQUEST'
export const FETCH_ALL_CATEGORY_SUCCESS = 'FETCH_ALL_CATEGORY_SUCCESS'
export const FETCH_ALL_CATEGORY_FAIL = 'FETCH_ALL_CATEGORY_FAIL'

export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAIL = 'FETCH_CATEGORY_FAIL'

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAIL    = 'UPDATE_CATEGORY_FAIL'
export const UPDATE_CATEGORY_RESET   = 'UPDATE_CATEGORY_RESET'