export const FETCH_ALL_CATEGORY_REQUEST = 'FETCH_ALL_CATEGORY_REQUEST'
export const FETCH_ALL_CATEGORY_SUCCESS = 'FETCH_ALL_CATEGORY_SUCCESS'
export const FETCH_ALL_CATEGORY_FAIL = 'FETCH_ALL_CATEGORY_FAIL'