export const COMMENT_CREATE_ON_POST_REQUEST = 'COMMENT_CREATE_ON_POST_REQUEST'
export const COMMENT_CREATE_ON_POST_SUCCESS = 'COMMENT_CREATE_ON_POST_SUCCESS'
export const COMMENT_CREATE_ON_POST_FAIL = 'COMMENT_CREATE_ON_POST_FAIL'

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL'