export const FETCH_ALL_POSTS_REQUEST = 'FETCH_ALL_POSTS_REQUEST'
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS'
export const FETCH_ALL_POSTS_FAIL = 'FETCH_ALL_POSTS_FAIL'

export const FETCH_FEATURED_POSTS_REQUEST = 'FETCH_FEATURED_POSTS_REQUEST'
export const FETCH_FEATURED_POSTS_SUCCESS = 'FETCH_FEATURED_POSTS_SUCCESS'
export const FETCH_FEATURED_POSTS_FAIL = 'FETCH_FEATURED_POSTS_FAIL'

export const FETCH_SINGLE_POST_REQUEST = 'FETCH_SINGLE_POST_REQUEST'
export const FETCH_SINGLE_POST_SUCCESS = 'FETCH_SINGLE_POST_SUCCESS'
export const FETCH_SINGLE_POST_FAIL     = 'FETCH_SINGLE_POST_FAIL'

export const FETCH_POSTS_BY_CATEGORY_REQUEST = 'FETCH_POSTS_BY_CATEGORY_REQUEST'
export const FETCH_POSTS_BY_CATEGORY_SUCCESS = 'FETCH_POSTS_BY_CATEGORY_SUCCESS'
export const FETCH_POSTS_BY_CATEGORY_FAIL     = 'FETCH_POSTS_BY_CATEGORY_FAIL'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL     = 'CREATE_POST_FAIL'